### ISSUE TITLE
Getting Client not authenticated to send anonymous mail during Email Notification through Jenkins

### ISSUE THREAD

**Issue by crazzytester** [Microsoft/vsts-jenkins-build-integration-sample#1]
Objective:- I want to trigger the Email Notification through jenkins as a post build action. I have made some research that after It migrates to O365 Accounts. SMTP Server is also updated, because I am getting an Error Message earlier when I am trying to test config the Email using SMTP Server and Port Name within my office.
I get something here https://superuser.com/questions/879361/how-to-configure-jenkins-email-notifications-through-outlook
Here is the Email Notification Configuration screenshot from Jenkins. 
![jenkinsemail_notif](https://user-images.githubusercontent.com/19578147/34098750-6c1b0598-e403-11e7-9ec1-cd64441ca70a.png)
I am creating a VSTS Build and running the Jenkins from there . Here is the Jenkins Build Error Log. Please ignore the Unstable Build Error. The Second Error is what I am facing for Email Notification.
[3_Queue Jenkins Job Vision_Smoke_Phase2.txt](https://github.com/Microsoft/vsts-jenkins-build-integration-sample/files/1567370/3_Queue.Jenkins.Job.Vision_Smoke_Phase2.txt)

Jenkins Console Output Error:-

com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [AM5PR06CA0015.eurprd06.prod.outlook.com]

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2057)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1580)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1097)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:131)
	at hudson.tasks.Mailer.perform(Mailer.java:170)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

**Comment by crazzytester** [comment]
@DavidStaheli  can you please look into this or assign to somebody :+1:
